services:
  - type: web
    name: compteur-des-api
    env: node
    buildCommand: npm install && cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production 