name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          npm install
          cd server && npm install

      - name: Build
        run: npm run build

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: server
          branch: gh-pages
          clean: true
          commit-message: "Deploy to GitHub Pages"
          force: true
          token: ${{ secrets.GITHUB_TOKEN }} 